### ISSUE TITLE
What's your motivation for this?

### ISSUE THREAD

**Issue by jhihn** [grassator/react-qml#1]
I'm just curious. It seems that given QML (which I admittedly consider superior) why would anyone want to use React in it? (Not "why React", but why combine them?)

**Comment by grassator** [comment]
I just wanted to understand React internals better and was also experimenting with QML at the time, so I just combined the two. No other real reason behind this.

**Comment by jhihn** [comment]
Ah, ok. If you were looking to re-use code, I was doing to recommend. QmlWeb ( https://github.com/qmlweb/qmlweb )
