### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by tungv** [grassator/react-qml#3]
Hi there,
I am building a react renderer targeting qml. I find that it has a similar goal with this project. Sadly, as I observe, this project is no longer developed in 3 years. So that's why I'm asking for the ownership of the npm package name `react-qml`. If you're willing to release and transfer it to my account at npm.im/~tungv, I will be very appreciated. If you're still want to keep it for future development of react renderer for qml, it'd be nice to keep in touch anyway.

Thank you,
Tung

**Comment by grassator** [comment]
I indeed do not plan to continue working on this and would happy to transfer ownership to any project that shows potential. Could you please provide a link to your implementation?

**Comment by tungv** [comment]
Hi @grassator 
The code can be found here: https://github.com/longseespace/qix

Basically, we build a react renderer using react 16 reconciler api. and generate react component class for most of the QtQuick controls.

There are some issues with composite properties like Popup's background.

**Comment by grassator** [comment]
@tungv I made you a collaborator, so now you should be push updates to react-qml. Please just make sure that you use at least version 0.2.0

**Comment by tungv** [comment]
thank you @grassator, I will start from the version 2.x to avoid confusions.
